services:
  mybundle_image_resizer.response_subscriber:
    class: MyBundle\ImageResizerBundle\EventSubscriber\ResponseSubscriber
    arguments:
      $parameterBag: "@parameter_bag"
    tags:
      - { name: kernel.event_subscriber }
