services:
  mybundle_image_resizer.image_resizer_subscriber:
    class: MyBundle\ImageResizerBundle\EventSubscriber\ImageResizerSubscriber
    arguments:
      $parameterBag: "@parameter_bag"
      $entityManager: "@doctrine.orm.entity_manager"

    tags:
      - { name: doctrine.event_subscriber, connection: default }
